### ISSUE TITLE
ServiceWorker registration failed

### ISSUE THREAD

**Issue by gavin-cooker** [chesscai/simple-pwa#1]
ServiceWorker registration failed:  DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

**Comment by gavin-cooker** [comment]
原来被注释掉了

**Comment by LinShouGui** [comment]
service-worker.tmpl又有什么用呢

**Comment by gavin-cooker** [comment]
不能离线访问啊,本地调试我只改了index.html里的    

    <script src="<%= htmlWebpackPlugin.files.publicPath %>register.simple.js"></script>
